image:
  repository: tccr.io/truecharts/elasticsearch
  pullPolicy: IfNotPresent
  tag: v8.10.2@sha256:0f4b76a1791bf9ca209773017266c28f5b1c8df3c2beb7ead8f7ce2a543f67e8

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 9200
        targetPort: 9200
        env:
          ELASTIC_PASSWORD:
            secretKeyRef:
              expandObjectName: "{{ if .Values.elasticsearchPassword }}true{{ else }}false{{ end }}"
              name: '{{ if .Values.elasticsearchPassword }}credentials{{ else if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ printf "%s-%s" .Release.Name "elasticsearchcreds" }}{{ end }}'
              key: "elasticsearch-password"

# -- Secret or password
# One of these options is required, unless used as a dependency for another TrueCharts chart.
elasticsearchPassword: ""
existingSecret: ""

persistence:
  data:
    enabled: true
    mountPath: "/usr/share/elasticsearch/data"

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
