image:
  repository: tccr.io/truecharts/elasticsearch
  pullPolicy: IfNotPresent
  tag: v8.10.2@sha256:78ccbbd6929a973685fcdbac44546620a37b047c44912f8637012c574b1eb635

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 9200
        protocol: tcp
        targetPort: 9200

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
