image:
  repository: tccr.io/truecharts/elasticsearch
  pullPolicy: IfNotPresent
  tag: v8.10.2@sha256:0f4b76a1791bf9ca209773017266c28f5b1c8df3c2beb7ead8f7ce2a543f67e8

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
    capabilities:
      add:
        - SYS_CHROOT

service:
  main:
    ports:
      main:
        port: 9200
        targetPort: 9200

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
