image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/zammad
  tag: latest@sha256:c9c8ec07af85ca06ff2776e1bd00c70cca470c7bf9aa92c716b78283bf880f49

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

zammad:
  zammad:
    zammad_autowizardjson: ""
  webconcurrency:
    webcon_instances: ""
    webcon_sessionjobs: 0
    webcon_schedprocesses: false
    webcon_delayedjobs: 0
  rails:
    rails_trustedproxies:
    - 127.0.0.1
    - ::1
  elasticsearch:
    elasticsearch_reindex: true

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          env:
            AUTOWIZARD_JSON: "{{ .Values.zammad.zammad.zammad_autowizardjson }}"
            ZAMMAD_WEB_CONCURRENCY: "{{ .Values.zammad.webconcurrency.webcon_instances }}"
            ZAMMAD_SESSION_JOBS_CONCURRENT: "{{ .Values.zammad.webconcurrency.webcon_sessionjobs }}"
            ZAMMAD_PROCESS_SCHEDULED_JOBS_WORKERS: "{{ .Values.zammad.webconcurrency.webcon_schedprocesses }}"
            ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS: "{{ .Values.zammad.webconcurrency.webcon_delayedjobs }}"
            RAILS_TRUSTED_PROXIES: '{{ toJson .Values.zammad.rails.rails_trustedproxies }}'
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
            MEMCACHE_SERVERS: '{{ printf "%v-%v:%v" .Release.Name "memcached" "11211" }}'
            ELASTICSEARCH_ENABLED: true
            ELASTICSEARCH_HOST: '{{ printf "%v-%v" .Release.Name "elasticsearch" }}'
            ELASTICSEARCH_PORT: 9200
            ELASTICSEARCH_SCHEMA: "http"
            ELASTICSEARCH_NAMESPACE: "zammad"
            ELASTICSEARCH_REINDEX: "{{ .Values.zammad.elasticsearch.elasticsearch_reindex }}"
            ELASTICSEARCH_SSL_VERIFY: true

persistence:
  data:
    enabled: true
    mountPath: /data
  redis-session:
    enabled: true
    type: configmap
    objectName: redis-session
    targetSelector:
      main:
        main:
          mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          subPath: redis-session.ini
          readOnly: true

portal:
  open:
    enabled: false

redis:
  enabled: true
  username: default